version: "3.9"  # Use the higher version for compatibility

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql
    hostname: sql
    networks:
      - network
    ports:
      - "1433:1433"
    volumes:
      - "mssqldata:/var/opt/mssql"
      - "./data:/data"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SQLS3rv3r
      - MSSQL_AGENT_ENABLED=true
      - MSSQL_PID=Express
    entrypoint:
      - /bin/bash
      - /data/entrypoint.sh
    command: [ "/opt/mssql/bin/sqlservr" ]

  coldfusion:
    image: adobecoldfusion/coldfusion2021
    container_name: coldfusion2021
    hostname: coldfusion2021
    networks:
      - network
    ports:
      - "8500:8500"
    volumes:
      - "./coldfusion-app:/app"
      - "./data:/data"
    environment:
      acceptEULA: "YES"
      password: "ColdFusion"
      enableSecureProfile: "false"
      installModules: sqlserver
    healthcheck:
      test: curl -f http://localhost/
      interval: 1m
      timeout: 3s
    depends_on:
      - sql

  react:
    stdin_open: true
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - network
    volumes:
      - "/app/node_modules"
      - "./react-app:/app"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mssqldata:

networks:
  network: